# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    sudo apt update -y
    # sudo apt install npm
    sudo curl --proto '=https' --tlsv1.3 https://sh.rustup.rs -sSf | sh -y
    sudo rustc --version
    sudo apt install cargo -y
    # sudo snap install zig --beta --classic
    # sudo cargo install cargo-lambda --locked
    sudo cargo --list


  displayName: 'Install Dependency'

# - script: |
#     sudo make package
#     sudo ls
#   displayName: 'Build Matano'
