# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    sudo apt update -y
    sudo apt install npm
    sudo apt install make
  displayName: 'Install Dependency'

- script: |
    sudo make package
    sudo ls
  displayName: 'Build Matano'
