# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# - task: Bash@3
#   displayName: 'Installing Node'
#   inputs:
#     targetType: 'inline'
#     script: |
#       sudo apt update -y
#       sudo apt install npm
      
# - task: Bash@3
#   displayName: 'Installing Rust'
#   inputs:
#     targetType: 'inline'
#     script: |
#       sudo curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain stable -y
#       source "$HOME/.cargo/env"
# - task: Bash@3
#   displayName: 'Installing Zig'
#   inputs:
#     targetType: 'inline'
#     script: |
#       sudo snap install zig --beta --classic
# - task: Bash@3
#   displayName: 'Installing Cargo Lambda'
#   inputs:
#     targetType: 'inline'
#     script: |
#       cargo install cargo-lambda

- task: Bash@3
  displayName: 'Creating Release file'
  inputs:
    targetType: 'inline'
    script: |
      # make package
      ls $(System.DefaultWorkingDirectory)

- task: GitHubRelease@1
  displayName: 'Publishing release'
  inputs:
    gitHubConnection: 'AbhayAgrawalT'
    repositoryName: 'AbhayAgrawalT/matano'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: 'v1.0.0'
    title: 'Test'
    assets: '$(System.DefaultWorkingDirectory)/*.yml'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'
# - script: |
#     sudo make package
#     sudo ls
#   displayName: 'Build Matano'
