# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      sudo apt update -y
      # sudo apt install npm
      sudo curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain stable -y
      # sudo apt install rustc
      # sudo apt install cargo -y
      # sudo snap install zig --beta --classic
      # sudo cargo install cargo-lambda
      # sudo rustc --version
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      sudo source "$HOME/.cargo/env"
      # sudo cargo install cargo-lambda
      sudo cargo --list

# - task: Bash@3
#   inputs:
#     targetType: 'inline'
#     script: |
#       sudo make package
#       sudo ls

# - script: |
#     sudo make package
#     sudo ls
#   displayName: 'Build Matano'
